spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 10
        min-idle: 10
        max-idle: 10
        max-wait: PT3S
        time-between-eviction-runs: PT5M
    timeout: PT3S